import { MeasurementAggregatedDto, MeasurementRawDto } from '../api/openAPI';

export type RawVariables = Omit<MeasurementRawDto, 'timestamp' | 'uptime'>;
export type AggregatedVariables = Omit<MeasurementAggregatedDto, 'timestamp' | 'uptime'>;

export const RawVariableLabelMap: Record<keyof RawVariables, string> = {
    voltagePhase1: 'Phase 1 Voltage',
    voltagePhase2: 'Phase 2 Voltage',
    voltagePhase3: 'Phase 3 Voltage',
    positiveActivePower: 'Positive Active Power',
    positiveActiveEnergyTotal: 'Positive Active Energy Total',
    negativeActivePower: 'Negative Active Power',
    negativeActiveEnergyTotal: 'Negative Active Energy Total',
    reactiveEnergyQuadrant1Total: 'Reactive Energy Quadrant 1 Total',
    reactiveEnergyQuadrant3Total: 'Reactive Energy Quadrant 3 Total',
    totalPower: 'Total Power',
    currentPhase1: 'Current Phase 1',
    currentPhase2: 'Current Phase 2',
    currentPhase3: 'Current Phase 3',
};

export const AggregatedVariableLabelMap: Record<keyof AggregatedVariables, string> = {
    minPositiveActivePower: 'Positive Active Power (min)',
    maxPositiveActivePower: 'Positive Active Power (max)',
    avgPositiveActivePower: 'Positive Active Power (avg)',
    medPositiveActivePower: 'Positive Active Power (med)',
    minPositiveActiveEnergyTotal: 'Positive Active Energy Total (min)',
    maxPositiveActiveEnergyTotal: 'Positive Active Energy Total (max)',
    avgPositiveActiveEnergyTotal: 'Positive Active Energy Total (avg)',
    medPositiveActiveEnergyTotal: 'Positive Active Energy Total (med)',
    minNegativeActivePower: 'Negative Active Power (min)',
    maxNegativeActivePower: 'Negative Active Power (max)',
    avgNegativeActivePower: 'Negative Active Power (avg)',
    medNegativeActivePower: 'Negative Active Power (med)',
    minNegativeActiveEnergyTotal: 'Negative Active Energy Total (min)',
    maxNegativeActiveEnergyTotal: 'Negative Active Energy Total (max)',
    avgNegativeActiveEnergyTotal: 'Negative Active Energy Total (avg)',
    medNegativeActiveEnergyTotal: 'Negative Active Energy Total (med)',
    minReactiveEnergyQuadrant1Total: 'Reactive Energy Quadrant 1 Total (min)',
    maxReactiveEnergyQuadrant1Total: 'Reactive Energy Quadrant 1 Total (max)',
    avgReactiveEnergyQuadrant1Total: 'Reactive Energy Quadrant 1 Total (avg)',
    medReactiveEnergyQuadrant1Total: 'Reactive Energy Quadrant 1 Total (med)',
    minReactiveEnergyQuadrant3Total: 'Reactive Energy Quadrant 3 Total (min)',
    maxReactiveEnergyQuadrant3Total: 'Reactive Energy Quadrant 3 Total (max)',
    avgReactiveEnergyQuadrant3Total: 'Reactive Energy Quadrant 3 Total (avg)',
    medReactiveEnergyQuadrant3Total: 'Reactive Energy Quadrant 3 Total (med)',
    minTotalPower: 'Total Power (min)',
    maxTotalPower: 'Total Power (max)',
    avgTotalPower: 'Total Power (avg)',
    medTotalPower: 'Total Power (med)',
    minCurrentPhase1: 'Current Phase 1 (min)',
    maxCurrentPhase1: 'Current Phase 1 (max)',
    avgCurrentPhase1: 'Current Phase 1 (avg)',
    medCurrentPhase1: 'Current Phase 1 (med)',
    minVoltagePhase1: 'Voltage Phase 1 (min)',
    maxVoltagePhase1: 'Voltage Phase 1 (max)',
    avgVoltagePhase1: 'Voltage Phase 1 (avg)',
    medVoltagePhase1: 'Voltage Phase 1 (med)',
    minCurrentPhase2: 'Current Phase 2 (min)',
    maxCurrentPhase2: 'Current Phase 2 (max)',
    avgCurrentPhase2: 'Current Phase 2 (avg)',
    medCurrentPhase2: 'Current Phase 2 (med)',
    minVoltagePhase2: 'Voltage Phase 2 (min)',
    maxVoltagePhase2: 'Voltage Phase 2 (max)',
    avgVoltagePhase2: 'Voltage Phase 2 (avg)',
    medVoltagePhase2: 'Voltage Phase 2 (med)',
    minCurrentPhase3: 'Current Phase 3 (min)',
    maxCurrentPhase3: 'Current Phase 3 (max)',
    avgCurrentPhase3: 'Current Phase 3 (avg)',
    medCurrentPhase3: 'Current Phase 3 (med)',
    minVoltagePhase3: 'Voltage Phase 3 (min)',
    maxVoltagePhase3: 'Voltage Phase 3 (max)',
    avgVoltagePhase3: 'Voltage Phase 3 (avg)',
    medVoltagePhase3: 'Voltage Phase 3 (med)',
    amountOfMeasurements: 'Amount of Measurements',
};
