import { MeasurementAggregatedDto, MeasurementRawDto } from '../api/openAPI';

export type RawVariables = Omit<MeasurementRawDto, 'timestamp'>;
export type AggregatedVariables = Omit<MeasurementAggregatedDto, 'timestamp' | 'amountOfMeasurements'>;

export const RawVariableLabelMap: Record<keyof RawVariables, string> = {
    voltagePhase1: 'Phase 1 Voltage',
    voltagePhase2: 'Phase 2 Voltage',
    voltagePhase3: 'Phase 3 Voltage',
    currentPhase1: 'Current Phase 1',
    currentPhase2: 'Current Phase 2',
    currentPhase3: 'Current Phase 3',
    positiveActivePower: 'Positive Active Power',
    negativeActivePower: 'Negative Active Power',
    positiveReactiveEnergyTotal: 'Positive Reactive Energy Total',
    negativeReactiveEnergyTotal: 'Negative Reactive Energy Total',
    positiveActiveEnergyTotal: 'Positive Active Energy Total',
    negativeActiveEnergyTotal: 'Negative Active Energy Total',
};

export const AggregatedVariableLabelMap: Record<keyof AggregatedVariables, string> = {
    minVoltagePhase1: 'Voltage Phase 1 (min)',
    maxVoltagePhase1: 'Voltage Phase 1 (max)',
    avgVoltagePhase1: 'Voltage Phase 1 (avg)',
    medVoltagePhase1: 'Voltage Phase 1 (med)',
    minVoltagePhase2: 'Voltage Phase 2 (min)',
    maxVoltagePhase2: 'Voltage Phase 2 (max)',
    avgVoltagePhase2: 'Voltage Phase 2 (avg)',
    medVoltagePhase2: 'Voltage Phase 2 (med)',
    minVoltagePhase3: 'Voltage Phase 3 (min)',
    maxVoltagePhase3: 'Voltage Phase 3 (max)',
    avgVoltagePhase3: 'Voltage Phase 3 (avg)',
    medVoltagePhase3: 'Voltage Phase 3 (med)',
    minCurrentPhase1: 'Current Phase 1 (min)',
    maxCurrentPhase1: 'Current Phase 1 (max)',
    avgCurrentPhase1: 'Current Phase 1 (avg)',
    medCurrentPhase1: 'Current Phase 1 (med)',
    minCurrentPhase2: 'Current Phase 2 (min)',
    maxCurrentPhase2: 'Current Phase 2 (max)',
    avgCurrentPhase2: 'Current Phase 2 (avg)',
    medCurrentPhase2: 'Current Phase 2 (med)',
    minCurrentPhase3: 'Current Phase 3 (min)',
    maxCurrentPhase3: 'Current Phase 3 (max)',
    avgCurrentPhase3: 'Current Phase 3 (avg)',
    medCurrentPhase3: 'Current Phase 3 (med)',
    minPositiveActivePower: 'Positive Active Power (min)',
    maxPositiveActivePower: 'Positive Active Power (max)',
    avgPositiveActivePower: 'Positive Active Power (avg)',
    medPositiveActivePower: 'Positive Active Power (med)',
    minNegativeActivePower: 'Negative Active Power (min)',
    maxNegativeActivePower: 'Negative Active Power (max)',
    avgNegativeActivePower: 'Negative Active Power (avg)',
    medNegativeActivePower: 'Negative Active Power (med)',
    minPositiveReactiveEnergyTotal: 'Positive Reactive Energy Total (min)',
    maxPositiveReactiveEnergyTotal: 'Positive Reactive Energy Total (max)',
    avgPositiveReactiveEnergyTotal: 'Positive Reactive Energy Total (avg)',
    medPositiveReactiveEnergyTotal: 'Positive Reactive Energy Total (med)',
    minNegativeReactiveEnergyTotal: 'Negative Reactive Energy Total (min)',
    maxNegativeReactiveEnergyTotal: 'Negative Reactive Energy Total (max)',
    avgNegativeReactiveEnergyTotal: 'Negative Reactive Energy Total (avg)',
    medNegativeReactiveEnergyTotal: 'Negative Reactive Energy Total (med)',
    minPositiveActiveEnergyTotal: 'Positive Active Energy Total (min)',
    maxPositiveActiveEnergyTotal: 'Positive Active Energy Total (max)',
    avgPositiveActiveEnergyTotal: 'Positive Active Energy Total (avg)',
    medPositiveActiveEnergyTotal: 'Positive Active Energy Total (med)',
    minNegativeActiveEnergyTotal: 'Negative Active Energy Total (min)',
    maxNegativeActiveEnergyTotal: 'Negative Active Energy Total (max)',
    avgNegativeActiveEnergyTotal: 'Negative Active Energy Total (avg)',
    medNegativeActiveEnergyTotal: 'Negative Active Energy Total (med)',
};
