/* tslint:disable */
/* eslint-disable */
/**
 * SMAIAX Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceConfigDto
 */
export interface DeviceConfigDto {
    /**
     * 
     * @type {string}
     * @memberof DeviceConfigDto
     */
    'encryptedMqttUsername'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceConfigDto
     */
    'encryptedMqttPassword'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceConfigDto
     */
    'topic'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeviceConfigDto
     */
    'publicKey'?: string | null;
}

