/* tslint:disable */
/* eslint-disable */
/**
 * SMAIAX Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const LocationResolution = {
    None: 'None',
    StreetName: 'StreetName',
    City: 'City',
    State: 'State',
    Country: 'Country',
    Continent: 'Continent'
} as const;

export type LocationResolution = typeof LocationResolution[keyof typeof LocationResolution];



