/* tslint:disable */
/* eslint-disable */
/**
 * SMAIAX Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MeasurementAggregatedDto } from './measurement-aggregated-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MeasurementRawDto } from './measurement-raw-dto';

/**
 * 
 * @export
 * @interface MeasurementListDto
 */
export interface MeasurementListDto {
    /**
     * 
     * @type {Array<MeasurementRawDto>}
     * @memberof MeasurementListDto
     */
    'measurementRawList'?: Array<MeasurementRawDto> | null;
    /**
     * 
     * @type {Array<MeasurementAggregatedDto>}
     * @memberof MeasurementListDto
     */
    'measurementAggregatedList'?: Array<MeasurementAggregatedDto> | null;
    /**
     * 
     * @type {number}
     * @memberof MeasurementListDto
     */
    'amountOfMeasurements'?: number;
}

