/* tslint:disable */
/* eslint-disable */
/**
 * SMAIAX Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MeasurementAggregatedDto
 */
export interface MeasurementAggregatedDto {
    /**
     * 
     * @type {string}
     * @memberof MeasurementAggregatedDto
     */
    'timestamp': string;
    /**
     * 
     * @type {string}
     * @memberof MeasurementAggregatedDto
     */
    'uptime': string;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minPositiveActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxPositiveActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgPositiveActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medPositiveActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minPositiveActiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxPositiveActiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgPositiveActiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medPositiveActiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minNegativeActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxNegativeActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgNegativeActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medNegativeActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minNegativeActiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxNegativeActiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgNegativeActiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medNegativeActiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minReactiveEnergyQuadrant1Total': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxReactiveEnergyQuadrant1Total': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgReactiveEnergyQuadrant1Total': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medReactiveEnergyQuadrant1Total': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minReactiveEnergyQuadrant3Total': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxReactiveEnergyQuadrant3Total': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgReactiveEnergyQuadrant3Total': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medReactiveEnergyQuadrant3Total': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minTotalPower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxTotalPower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgTotalPower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medTotalPower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minCurrentPhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxCurrentPhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgCurrentPhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medCurrentPhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minVoltagePhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxVoltagePhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgVoltagePhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medVoltagePhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minCurrentPhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxCurrentPhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgCurrentPhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medCurrentPhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minVoltagePhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxVoltagePhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgVoltagePhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medVoltagePhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minCurrentPhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxCurrentPhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgCurrentPhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medCurrentPhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'minVoltagePhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'maxVoltagePhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'avgVoltagePhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'medVoltagePhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementAggregatedDto
     */
    'amountOfMeasurements': number;
}

