/* tslint:disable */
/* eslint-disable */
/**
 * SMAIAX Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MeasurementRawDto
 */
export interface MeasurementRawDto {
    /**
     * 
     * @type {string}
     * @memberof MeasurementRawDto
     */
    'timestamp': string;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'voltagePhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'voltagePhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'voltagePhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'currentPhase1': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'currentPhase2': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'currentPhase3': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'positiveActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'negativeActivePower': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'positiveReactiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'negativeReactiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'positiveActiveEnergyTotal': number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementRawDto
     */
    'negativeActiveEnergyTotal': number;
}

