/* tslint:disable */
/* eslint-disable */
/**
 * SMAIAX Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const MeasurementResolution = {
    Raw: 'Raw',
    Minute: 'Minute',
    QuarterHour: 'QuarterHour',
    Hour: 'Hour',
    Day: 'Day',
    Week: 'Week'
} as const;

export type MeasurementResolution = typeof MeasurementResolution[keyof typeof MeasurementResolution];



